services:
  - type: web
    name: discord-oauth-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: CLIENT_ID
        value: your_discord_client_id
      - key: CLIENT_SECRET
        value: your_discord_client_secret
      - key: REDIRECT_URI
        value: https://your-app.onrender.com/oauth/callback
